"""Surface protocols: the seam that permits a future desktop implementation."""

from __future__ import annotations

from typing import Protocol

from interface_cua.schema.artifact import TargetStrategy


class SurfaceElement(Protocol):
    @property
    def description(self) -> str: ...

    async def click(self) -> None: ...

    async def fill(self, value: str) -> None: ...

    async def select(self, value: str) -> None: ...

    async def text(self) -> str: ...

    async def is_visible(self) -> bool: ...

    async def is_enabled(self) -> bool: ...


class SurfaceAdapter(Protocol):
    @property
    def current_url(self) -> str: ...

    async def find(self, strategy: TargetStrategy, frame: str | None) -> list[SurfaceElement]: ...

    async def page_text(self) -> str: ...

    async def navigate(self, url: str) -> None: ...

    async def keypress(self, key: str) -> None: ...

    async def wait_until_settled(self, timeout_ms: int) -> None: ...

    async def screenshot(self) -> bytes: ...

    async def dom_snapshot(self) -> str: ...

